### PR TITLE
Some adjustments due to the move

### LINKED ISSUE #10: Some adjustments due to the move
- [x] Cargo.toml
- [x] kotosiro -> delta_sharing
- [x] README.md

~GitHub actions~
~DockerHub~

### PR DESCRIPTION
**Pull request by ognis1205**
Close #10

### CODE REVIEW

**Comment by ognis1205** [comment]
@rtyler 
Would you mind if I ask you add me as the default reviewer on this repository?
Thanks in advance.

**Comment by ognis1205** [comment]
Would you mind if I ask you to approve this PR? @rtyler @MrPowers

**Review by roeap — APPROVED** [review]
Just skimmed it, hoping to get more into it soon :)

**Comment by ognis1205** [comment]
> Just skimmed it, hoping to get more into it soon :)

Thanks Robert!

**Review by rtyler — APPROVED** [review]

**Pull request merged**
